---
- name: Mysql DB Initialization Script for New Instances
  hosts: all
  tasks:
    - name: Create Application User
      community.mysql.mysql_user:
        login_host: "{{ db_host }}"
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        name: "{{ application_user }}"
        host: "{{ item.host }}"
        password: "{{ application_password }}"
        priv: |
          {{ database }}.*: SELECT, ALTER, CREATE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EXECUTE, INSERT, SHOW VIEW, TRIGGER, UPDATE, USAGE, LOAD FROM S3
      with_items:
      - { host: "192.168.%"}
      - { host: "10.10.%"}

    - name: Create DBA database
      community.mysql.mysql_db:   
        login_host: "{{ db_host }}"
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        name: "DBA"   

    - name: Create DBA Users
      community.mysql.mysql_user:
        login_host: "{{ db_host }}"
        login_user: "{{ db_username }}"
        login_password: "{{ db_password }}"
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        password: "{{ item.password }}"
        priv: '*.*:GRANT, SELECT, CREATE, CREATE TEMPORARY TABLES, CREATE VIEW, UPDATE, INSERT, ALTER, DELETE, DROP, EXECUTE, SHOW VIEW, TRIGGER, SHOW DATABASES, ALTER ROUTINE, CREATE ROUTINE, CREATE USER, EVENT, INDEX, LOCK TABLES, PROCESS, REFERENCES, RELOAD'
      with_items:
      - { host: "192.168.%", name: "randoneering_dba", password: "{{ randoneering_pw }}"}
      - { host: "10.10.%", name: "randoneering_dba", password: "{{ randoneering_pw }}"}
      no_log: true




