---
- hosts: all
  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Ping Discord Server Status
      community.general.discord:
        webhook_id: "{{ WEBHOOK_ID }}"
        webhook_token: "{{ WEBHOOK_TOKEN }}"
        content: "{{ disk_usage }} for {{ host }}"