---
- hosts: all
  tasks:
  - name: Check disk space available
    ansible.builtin.shell:
      cmd: |
        set -euo pipefail
        df -Ph / | awk 'NR==2 {print $5}'
      executable: /bin/bash
    changed_when: false
    check_mode: false
    register: disk_usage

  - name: 85% Utilization Check
    community.general.discord:
      webhook_id: "{{ webhook_id }}"
      webhook_token: "{{ webhook_token }}"
      content: "Disk usage for {{ host }} is {{ disk_usage }}" 